@startuml
'https://plantuml.com/sequence-diagram

autonumber
loop n times
    activate GridSim
    GridSim -> GridSim: Get Load Profiles for Timestep
    GridSim -> GridSim: Power Flow Calculation
    GridSim -> GridSim: Extract Measurements and create SMGW JSON objects
    GridSim -> NetSim: Pass JSON measurement data
    activate NetSim
    activate "Tap Device"
    deactivate GridSim
    NetSim -> NetSim: Simulate sending of measurement data to Grid Operator
    autonumber 5
    NetSim -> "Tap Device": Send measurement data
    "Tap Device" -> NetSim: Conduct FDIA
    NetSim -> GridSim: Send back data received by Grid Operator
    activate GridSim
    deactivate NetSim
    deactivate "Tap Device"
    GridSim -> GridSim: Run Bad Data Detection
    GridSim -> GridSim: Run State Estimation
end
@enduml