@startuml
'https://plantuml.com/activity-diagram-beta

start
partition Setup{
    :Wait for message with n;
    :Create n+1 nodes;
    :Install Point-to-Point Channels;
    :Install Internet Stack;
}
partition Simulation{
    if (GO Node) then (yes)
    :Install NetSimSinkApp;
    :Collect Messages as JSON Objects;
    :Send JSON List back to GridSim;
    else (no)
    :Install NetSimApp;
    :Load TAC 14 JSON Data;
    :Wrap TAC 14 Data in TCP Packets;
    :Send TAC 14 Packets to Grid Operator Node;
    endif
}
stop

@enduml
