@startuml
'https://plantuml.com/sequence-diagram

autonumber
loop n times
    activate GridSim
    GridSim -> GridSim: Get Load Profiles for Timestep
    GridSim -> GridSim: Power Flow Calculation
    GridSim -> GridSim: Extract Measurements and create SMGW JSON objects
    GridSim --> GridSim: Insert False Data into JSON measurement data
    GridSim -> NetSim: Load JSON measurement data
    activate NetSim
    deactivate GridSim
    NetSim -> NetSim: Simulate sending of measurement data to Grid Operator
    NetSim -> NetSim: Create JSON file of data received by Grid Operator
    NetSim -> GridSim: Load JSON data received by Grid Operator
    activate GridSim
    deactivate NetSim
    GridSim -> GridSim: Run Bad Data Detection
    GridSim -> GridSim: Run State Estimation
end
@enduml