@startuml
'https://plantuml.com/sequence-diagram

activate GridSim
loop n times
    GridSim -> GridSim: Get Load Profiles for Timestep
    GridSim -> GridSim: Power Flow Calculation
    GridSim -> GridSim: Check Grid Health
    GridSim -> GridSim: Extract Measurements and create SMGW JSON objects
    GridSim --> GridSim: Insert False Data into JSON measurement data
    activate NetSim
    NetSim -> NetSim: Start listening for incoming data
    GridSim -> NetSim: Send JSON measurement data as TCP packets
    NetSim -> NetSim: Parse JSON measurement data
    NetSim -> NetSim: Simulate sending of measurement data to Grid Operator
    GridSim -> GridSim: Start listening for incoming data
    NetSim -> NetSim: Congregate JSON of data received by Grid Operator
    NetSim -> GridSim: Send back data received by Grid Operator
    GridSim -> GridSim: Parse JSON Grid Operator Data
    deactivate NetSim
    GridSim -> GridSim: Run Bad Data Detection
    GridSim -> GridSim: Run State Estimation
end
deactivate GridSim
@enduml