@startuml
'https://plantuml.com/activity-diagram-beta
start
while (Load Data Available)
    partition "Creation of Measurements" {
        :Get Data from Simbench Load Profile;
        :Run Power Flow Calculation;
        :Check Grid Health;
        :Select Busses with SMGW;
        :Create Measurement Data from Power Flow;
        if (FDIA) then (yes)
            :Inject FDIA Measurements into Measurement Data;
        else (no)
        endif
            :Build SMGW JSON Files;
    }
    :Send to Communication Simulator;
    :Take Grid Operator Data from Communication Simulator;
    partition "State Estimation" {
        :Run Bad Data Detection;
        :Run State Estimation;
        :Plot Effect;
    }
endwhile
stop

@enduml
